"""initial

Revision ID: 02defd0699aa
Revises: 
Create Date: 2025-05-27 22:15:03.697240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02defd0699aa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('osm_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_admin', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('osm_id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_token'), ['token'], unique=True)

    op.create_table('plugin',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('homepage', sa.String(), nullable=True),
    sa.Column('country', sa.String(length=32), nullable=True),
    sa.Column('hidden', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('icon', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.osm_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('plugin_version',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('plugin_id', sa.String(), nullable=False),
    sa.Column('created_on', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('downloads', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('changelog', sa.String(), nullable=True),
    sa.Column('experimental', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.osm_id'], ),
    sa.ForeignKeyConstraint(['plugin_id'], ['plugin.id'], ),
    sa.PrimaryKeyConstraint('pk')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plugin_version')
    op.drop_table('plugin')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_token'))

    op.drop_table('user')
    # ### end Alembic commands ###
